### PR TITLE
Corrected bump2version segment in CI pipeline

### PR DESCRIPTION
**Pull request by kmiller96**
There is a typo where the bump performed is a minor bump, but the surrounding documentation suggests it should be a major bump.

### CODE REVIEW

**Review by joaomcteixeira — APPROVED** [review]
You are totally right, @kmiller96. Thanks so much for your input. I hope you are finding this repository useful for your projects and learning.
Best,

**Comment by joaomcteixeira** [comment]
Could you add a summary of your additions to the `CHANGELOG.rst` as described here?

https://python-project-skeleton.readthedocs.io/en/latest/contributing.html#update-changelog

Otherwise, I will do :wink:

**Comment by kmiller96** [comment]
@joaomcteixeira I have made the requested changes and have rerequested your review.

**Review by joaomcteixeira — APPROVED** [review]

**Comment by kmiller96** [comment]
Whoops! Thanks for those corrections :)

**Pull request merged**
